### PR TITLE
I call him bop bop

### PR DESCRIPTION
**Pull request by dxa59**

### CODE REVIEW

**Comment by dxa59** [comment]
merge u noob

**Comment by nathandonato** [comment]
"ayy lmao" not "AYY LMAO" sorry

**Comment by dxa59** [comment]
u cant change the rules

https://github.com/nathandonato/ayy/commit/e87e4c46524a47cda8838eb12a9ab48b7481193f

**Comment by nathandonato** [comment]
reopening

**Comment by dxa59** [comment]
AND I QUOTE

+*YOU MUST SAY AYY LMAO*

**Comment by nathandonato** [comment]
reclosing

**Comment by buckyoung** [comment]
nice catch @dxa59

**Pull request closed without merging**
