### PR TITLE
Update ayy.php

### PR DESCRIPTION
**Pull request by buckyoung**

### CODE REVIEW

**Comment by nathandonato** [comment]
i appreciate your vehement adherence to the rules, but they don't need to be in ayy.php

**Comment by buckyoung** [comment]
Seems like a good place for them. I suggest we seriously consider this change instead of blindly closing PRs for ppl that are trying their best here

**Comment by nathandonato** [comment]
you're the blind one ok

**Comment by buckyoung** [comment]
i dictated this PR to siri.... was there an issue?

**Comment by dxa59** [comment]
nathandonato is a tyrant

**Comment by buckyoung** [comment]
@nathandonato is def a tyrant, look at this @dxa59 

screen shot 2015-10-15 at 1 22 04 pm

**Comment by buckyoung** [comment]
this community needs some work

**Pull request closed without merging**
